# Generated by Django 5.0.3 on 2024-04-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="Username")),
                ("password", models.CharField(max_length=50, verbose_name="Password")),
            ],
        ),
    ]
