# Generated by Django 5.0.3 on 2024-04-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounts",
            options={"verbose_name_plural": "Accounts"},
        ),
        migrations.AddField(
            model_name="accounts",
            name="state",
            field=models.IntegerField(default=0, verbose_name="State"),
        ),
    ]
