# Generated by Django 5.0.3 on 2024-04-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="receits",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("products", models.CharField(max_length=50, verbose_name="Products")),
                ("amounts", models.CharField(max_length=50, verbose_name="Amounts")),
                ("prices", models.CharField(max_length=50, verbose_name="Prices")),
            ],
            options={
                "verbose_name_plural": "Receits",
            },
        ),
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name_plural": "Products"},
        ),
        migrations.AlterField(
            model_name="products",
            name="amount",
            field=models.IntegerField(verbose_name="amount"),
        ),
        migrations.AlterField(
            model_name="products",
            name="type",
            field=models.CharField(
                choices=[("manfz", "Manfaz"), ("foram", "Foram")],
                default="manfz",
                max_length=9,
            ),
        ),
    ]
