# Generated by Django 5.0.3 on 2024-04-03 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_receits_alter_products_options_alter_products_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receits",
            name="Date",
            field=models.DateField(
                default=datetime.date(2024, 4, 3), verbose_name="Date"
            ),
        ),
        migrations.AddField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="12:05:08", verbose_name="Time"),
        ),
    ]
