# Generated by Django 5.0.3 on 2024-04-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_receits_date_receits_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="receits",
            name="intotal",
            field=models.FloatField(default=0, verbose_name="Total Money"),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.FloatField(verbose_name="Price"),
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="12:39:17", verbose_name="Time"),
        ),
    ]
