# Generated by Django 5.0.3 on 2024-04-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_receits_intotal_alter_products_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="username",
            field=models.CharField(max_length=50, verbose_name="Nickname"),
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="13:13:49", verbose_name="Time"),
        ),
    ]
