# Generated by Django 5.0.3 on 2024-04-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_accounts_username_alter_receits_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="Nickname",
            field=models.CharField(
                default="user", max_length=50, verbose_name="Nickname"
            ),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="username",
            field=models.CharField(max_length=50, verbose_name="Username"),
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="13:14:51", verbose_name="Time"),
        ),
    ]
