# Generated by Django 5.0.3 on 2024-04-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_employees_alter_receits_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="employees",
            name="username",
            field=models.CharField(default="", max_length=50, verbose_name="Username"),
        ),
        migrations.AlterField(
            model_name="employees",
            name="nickname",
            field=models.CharField(default="", max_length=50, verbose_name="Nickname"),
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="14:23:18", verbose_name="Time"),
        ),
    ]
