# Generated by Django 5.0.3 on 2024-04-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_employees_username_alter_employees_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="Money",
            field=models.FloatField(verbose_name="Money IN / OUT"),
        ),
        migrations.AlterField(
            model_name="employees",
            name="nickname",
            field=models.CharField(
                default="", max_length=50, unique=True, verbose_name="Nickname"
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="username",
            field=models.CharField(
                default="", max_length=50, unique=True, verbose_name="Username"
            ),
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="14:25:44", verbose_name="Time"),
        ),
    ]
