# Generated by Django 5.0.3 on 2024-04-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_remove_employees_money_employees_moneyminus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receits",
            name="seller",
            field=models.CharField(
                default="unknwon", max_length=50, verbose_name="Seller"
            ),
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="15:46:42", verbose_name="Time"),
        ),
    ]
