# Generated by Django 5.0.3 on 2024-04-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0014_receits_seller_alter_receits_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift_finishing",
            name="finishing",
            field=models.BooleanField(default=False, verbose_name="Finishing State"),
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="16:34:27", verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="shift_finishing",
            name="user",
            field=models.CharField(max_length=50, verbose_name="Current User"),
        ),
    ]
