# Generated by Django 5.0.3 on 2024-04-03 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_shift_finishing_finishing_alter_receits_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="deletedReceits",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("uid", models.IntegerField(unique=True, verbose_name="UID")),
                (
                    "Date",
                    models.DateField(
                        default=datetime.date(2024, 4, 3), verbose_name="Date"
                    ),
                ),
                ("time", models.TimeField(default="17:37:17", verbose_name="Time")),
                (
                    "seller",
                    models.CharField(
                        default="unknwon", max_length=50, verbose_name="Seller"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Deleted Receits",
            },
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="17:37:17", verbose_name="Time"),
        ),
    ]
