# Generated by Django 5.0.3 on 2024-04-04 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_deletedreceits_alter_receits_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift_finishing",
            name="password",
            field=models.CharField(
                default="yasminsabry", max_length=50, verbose_name="Password"
            ),
        ),
        migrations.AlterField(
            model_name="deletedreceits",
            name="Date",
            field=models.DateField(
                default=datetime.date(2024, 4, 4), verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="deletedreceits",
            name="time",
            field=models.TimeField(default="08:06:57", verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Product Name"
            ),
        ),
        migrations.AlterField(
            model_name="receits",
            name="Date",
            field=models.DateField(
                default=datetime.date(2024, 4, 4), verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="08:06:57", verbose_name="Time"),
        ),
    ]
