# Generated by Django 5.0.3 on 2024-04-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_shift_finishing_password_alter_deletedreceits_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deletedreceits",
            name="amounts",
            field=models.CharField(default="", max_length=50, verbose_name="Amounts"),
        ),
        migrations.AddField(
            model_name="deletedreceits",
            name="intotal",
            field=models.FloatField(default=0, verbose_name="Total Money"),
        ),
        migrations.AddField(
            model_name="deletedreceits",
            name="prices",
            field=models.CharField(default="", max_length=50, verbose_name="Prices"),
        ),
        migrations.AddField(
            model_name="deletedreceits",
            name="products",
            field=models.CharField(default="", max_length=50, verbose_name="Products"),
        ),
        migrations.AlterField(
            model_name="deletedreceits",
            name="time",
            field=models.TimeField(default="10:45:43", verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="10:45:43", verbose_name="Time"),
        ),
    ]
