# Generated by Django 5.0.3 on 2024-04-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0018_deletedreceits_amounts_deletedreceits_intotal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deletedreceits",
            name="time",
            field=models.TimeField(default="12:18:03", verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="12:18:03", verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="shift_finishing",
            name="ReceitsCount",
            field=models.IntegerField(default=0, verbose_name="No of Receits "),
        ),
        migrations.AlterField(
            model_name="shift_finishing",
            name="totalMoney",
            field=models.FloatField(default=0, verbose_name="Total Money"),
        ),
        migrations.AlterField(
            model_name="shift_finishing",
            name="user",
            field=models.CharField(
                default="default", max_length=50, verbose_name="Current User"
            ),
        ),
    ]
