# Generated by Django 5.0.3 on 2024-04-04 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_alter_deletedreceits_time_alter_receits_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="gavedMoney",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("intotal", models.FloatField(default=0, verbose_name="Total Money")),
                (
                    "Date",
                    models.DateField(
                        default=datetime.date(2024, 4, 4), verbose_name="Date"
                    ),
                ),
                ("time", models.TimeField(default="12:34:34", verbose_name="Time")),
                (
                    "gaver",
                    models.CharField(
                        default="default", max_length=50, verbose_name="Gaver"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Deleted Receits",
            },
        ),
        migrations.AlterField(
            model_name="deletedreceits",
            name="time",
            field=models.TimeField(default="12:34:34", verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="12:34:34", verbose_name="Time"),
        ),
    ]
