# Generated by Django 5.0.3 on 2024-04-04 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0020_gavedmoney_alter_deletedreceits_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="inOutEmployeeHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "inOutMoney",
                    models.FloatField(default=0, verbose_name="IN / OUT Money"),
                ),
                (
                    "Date",
                    models.DateField(
                        default=datetime.date(2024, 4, 4), verbose_name="Date"
                    ),
                ),
                ("time", models.TimeField(default="13:07:27", verbose_name="Time")),
                (
                    "seller",
                    models.CharField(
                        default="default", max_length=50, verbose_name="Seller"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "IN/OUT Employee History",
            },
        ),
        migrations.AlterModelOptions(
            name="gavedmoney",
            options={"verbose_name_plural": "Gaved Money"},
        ),
        migrations.AlterField(
            model_name="deletedreceits",
            name="time",
            field=models.TimeField(default="13:07:27", verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="gavedmoney",
            name="intotal",
            field=models.FloatField(default=0, verbose_name="Money"),
        ),
        migrations.AlterField(
            model_name="gavedmoney",
            name="time",
            field=models.TimeField(default="13:07:27", verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="13:07:27", verbose_name="Time"),
        ),
    ]
