# Generated by Django 5.0.3 on 2024-04-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_inoutemployeehistory_alter_gavedmoney_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inoutemployeehistory",
            name="existedMoney",
            field=models.IntegerField(default=0, verbose_name="Bank Money"),
        ),
        migrations.AddField(
            model_name="inoutemployeehistory",
            name="givenMoney",
            field=models.IntegerField(default=0, verbose_name="Device Money"),
        ),
        migrations.AddField(
            model_name="inoutemployeehistory",
            name="totalMoney",
            field=models.IntegerField(default=0, verbose_name="Device Money"),
        ),
        migrations.AlterField(
            model_name="deletedreceits",
            name="time",
            field=models.TimeField(default="16:21:08", verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="gavedmoney",
            name="time",
            field=models.TimeField(default="16:21:08", verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="inoutemployeehistory",
            name="time",
            field=models.TimeField(default="16:21:08", verbose_name="Time"),
        ),
        migrations.AlterField(
            model_name="receits",
            name="time",
            field=models.TimeField(default="16:21:08", verbose_name="Time"),
        ),
    ]
