# Generated by Django 5.0.3 on 2024-04-15 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_inoutemployeehistory_existedmoney_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishingHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='default', max_length=45, verbose_name='Casher Name')),
                ('Date', models.DateField(default=datetime.date(2024, 4, 15), verbose_name='Date')),
                ('time', models.TimeField(default='15:22:59', verbose_name='Time')),
                ('existedMoney', models.IntegerField(default=0, verbose_name='Existed Money')),
                ('inOutUser', models.FloatField(default=0, verbose_name='IN / OUT Money')),
            ],
            options={
                'verbose_name_plural': 'End Shifting History',
            },
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 15), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default='15:22:59', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='receitsCount',
            field=models.IntegerField(default=0, verbose_name='No of Receits '),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 15), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default='15:22:59', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 15), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='givenMoney',
            field=models.IntegerField(default=0, verbose_name='Given Money'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default='15:22:59', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 15), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default='15:22:59', verbose_name='Time'),
        ),
    ]
