# Generated by Django 5.0.3 on 2024-04-16 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_finishinghistory_alter_deletedreceits_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishinghistory',
            name='gavedMoney',
            field=models.FloatField(default=0, verbose_name='Gaved Money'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 16), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default='07:48:51', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 16), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='existedMoney',
            field=models.FloatField(default=0, verbose_name='Existed Money'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default='07:48:51', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 16), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default='07:48:51', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 16), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='existedMoney',
            field=models.FloatField(default=0, verbose_name='Bank Money'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='givenMoney',
            field=models.FloatField(default=0, verbose_name='Given Money'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default='07:48:51', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='totalMoney',
            field=models.FloatField(default=0, verbose_name='Device Money'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 16), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default='07:48:51', verbose_name='Time'),
        ),
    ]
