# Generated by Django 5.0.3 on 2024-04-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_finishinghistory_gavedmoney_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarabeza_users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='default', max_length=45, verbose_name='Tarbeza User')),
                ('inOutUser', models.FloatField(default=0, verbose_name='IN / OUT Money')),
            ],
            options={
                'verbose_name_plural': 'Tarbeeza Users',
            },
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default='20:00:05', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default='20:00:05', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default='20:00:05', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default='20:00:05', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default='20:00:05', verbose_name='Time'),
        ),
    ]
