# Generated by Django 5.0.3 on 2024-04-24 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_gotover_alter_deletedreceits_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountAdjusting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='default', max_length=45, verbose_name='Supervisor')),
                ('amount', models.IntegerField(verbose_name='Current amount')),
                ('adjustedAmount', models.IntegerField(verbose_name='Adjusted amount')),
                ('Date', models.DateField(default=datetime.date(2024, 4, 24), verbose_name='Date')),
                ('time', models.TimeField(default='16:57:52', verbose_name='Time')),
            ],
            options={
                'verbose_name_plural': 'Amount Adjusting',
            },
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 24), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default='16:57:52', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 24), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default='16:57:52', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 24), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default='16:57:52', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 24), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='time',
            field=models.TimeField(default='16:57:52', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 24), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default='16:57:52', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 4, 24), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default='16:57:52', verbose_name='Time'),
        ),
    ]
