# Generated by Django 5.0.3 on 2024-04-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_amountadjusting_alter_deletedreceits_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountadjusting',
            name='product',
            field=models.CharField(default='default', max_length=45, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='time',
            field=models.TimeField(default='17:00:06', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default='17:00:06', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default='17:00:06', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default='17:00:06', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='time',
            field=models.TimeField(default='17:00:06', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default='17:00:06', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default='17:00:06', verbose_name='Time'),
        ),
    ]
