# Generated by Django 5.0.3 on 2024-04-29 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_marakez_products_alter_amountadjusting_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='marakez_receits',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('products', models.CharField(max_length=50, verbose_name='Products')),
                ('amounts', models.CharField(max_length=50, verbose_name='Amounts')),
                ('prices', models.CharField(max_length=50, verbose_name='Prices')),
                ('intotal', models.FloatField(default=0, verbose_name='Total Money')),
                ('seller', models.CharField(default='unknwon', max_length=50, verbose_name='Seller')),
                ('Date', models.DateField(default=datetime.datetime(2024, 4, 29, 4, 38, 7, 225728), verbose_name='Date')),
                ('time', models.TimeField(default='04:38:07', verbose_name='Time')),
            ],
            options={
                'verbose_name_plural': 'Marakez Receits',
            },
        ),
        migrations.AlterModelOptions(
            name='marakez_products',
            options={'verbose_name_plural': 'Markez Products'},
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 4, 38, 7, 224230), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='time',
            field=models.TimeField(default='04:38:07', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 4, 38, 7, 208609), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default='04:38:07', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 4, 38, 7, 208609), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default='04:38:07', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 4, 38, 7, 208609), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default='04:38:07', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 4, 38, 7, 208609), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='time',
            field=models.TimeField(default='04:38:07', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 4, 38, 7, 208609), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default='04:38:07', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 4, 29, 4, 38, 7, 208609), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default='04:38:07', verbose_name='Time'),
        ),
    ]
