# Generated by Django 5.0.3 on 2024-05-03 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_marakez_names_alter_amountadjusting_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='marakez_booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('BookerName', models.CharField(max_length=50, verbose_name='Booker Name')),
                ('products', models.CharField(max_length=50, verbose_name='Products')),
                ('amounts', models.CharField(max_length=50, verbose_name='Amounts')),
                ('prices', models.CharField(max_length=50, verbose_name='Prices')),
                ('intotal', models.FloatField(default=0, verbose_name='Total Money')),
                ('seller', models.CharField(default='unknwon', max_length=50, verbose_name='Seller')),
                ('Date', models.DateField(default=datetime.datetime(2024, 5, 3, 10, 46, 55, 844441), verbose_name='Date')),
                ('time', models.TimeField(default='10:46:55', verbose_name='Time')),
                ('state', models.BooleanField(default=False, verbose_name='State')),
            ],
            options={
                'verbose_name_plural': 'Marakez Booking :)',
            },
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 10, 46, 55, 844441), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='time',
            field=models.TimeField(default='10:46:55', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 10, 46, 55, 844441), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default='10:46:55', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 10, 46, 55, 844441), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default='10:46:55', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 10, 46, 55, 844441), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default='10:46:55', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 10, 46, 55, 844441), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='time',
            field=models.TimeField(default='10:46:55', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 10, 46, 55, 844441), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default='10:46:55', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 10, 46, 55, 844441), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='time',
            field=models.TimeField(default='10:46:55', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 5, 3, 10, 46, 55, 842391), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default='10:46:55', verbose_name='Time'),
        ),
    ]
