# Generated by Django 5.0.3 on 2024-06-21 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_amountadjusting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receits',
            name='rtype',
            field=models.CharField(default='--', max_length=150, verbose_name='Types'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 3, 5, 20, 300323), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='time',
            field=models.TimeField(default='03:05:20', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 3, 5, 20, 297331), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default='03:05:20', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 3, 5, 20, 299325), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default='03:05:20', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 3, 5, 20, 298328), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default='03:05:20', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 3, 5, 20, 299325), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='time',
            field=models.TimeField(default='03:05:20', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 3, 5, 20, 298328), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default='03:05:20', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 3, 5, 20, 302317), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='time',
            field=models.TimeField(default='03:05:20', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 3, 5, 20, 301320), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='time',
            field=models.TimeField(default='03:05:20', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 6, 21, 3, 5, 20, 296333), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default='03:05:20', verbose_name='Time'),
        ),
    ]
