# Generated by Django 5.0.3 on 2024-07-24 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_receits_rtype_alter_amountadjusting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountadjusting',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 20, 38, 56, 487895), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='time',
            field=models.TimeField(default='20:38:56', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 20, 38, 56, 482898), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default='20:38:56', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 20, 38, 56, 485897), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default='20:38:56', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 20, 38, 56, 483898), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default='20:38:56', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 20, 38, 56, 486896), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='time',
            field=models.TimeField(default='20:38:56', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 20, 38, 56, 484897), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default='20:38:56', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 20, 38, 56, 490894), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='time',
            field=models.TimeField(default='20:38:56', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 20, 38, 56, 489894), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='time',
            field=models.TimeField(default='20:38:56', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('manfz', 'Manfaz'), ('foram', 'Foram'), ('offers', 'offers')], default='manfz', max_length=9),
        ),
        migrations.AlterField(
            model_name='receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 7, 24, 20, 38, 56, 480899), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default='20:38:56', verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='shift_finishing',
            name='password',
            field=models.CharField(default='asmaagalal', max_length=50, verbose_name='Password'),
        ),
    ]
