# Generated by Django 5.0.3 on 2024-09-12 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_amountadjusting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receits',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 12, 28, 49, 824602, tzinfo=datetime.timezone.utc), verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 28, 49, 828602), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 28, 49, 828602, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 28, 49, 825602), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 28, 49, 825602, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 28, 49, 827603), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 28, 49, 827603, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 28, 49, 826601), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 28, 49, 826601, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 28, 49, 828602), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 28, 49, 828602, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 28, 49, 827603), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 28, 49, 827603, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 28, 49, 831600), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 28, 49, 831600, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 28, 49, 829599), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 28, 49, 829599, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 28, 49, 824602), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 28, 49, 824602, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='shift_finishing',
            name='password',
            field=models.CharField(default='robochat', max_length=50, verbose_name='Password'),
        ),
    ]
