# Generated by Django 5.0.3 on 2024-09-12 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_receits_datetime_alter_amountadjusting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receits',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Starting Point'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 31, 1, 105902), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 31, 1, 105902, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 31, 1, 101905), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 31, 1, 101905, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 31, 1, 104903), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 31, 1, 104903, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 31, 1, 102903), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 31, 1, 102903, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 31, 1, 105902), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 31, 1, 105902, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 31, 1, 103903), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 31, 1, 103903, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 31, 1, 108903), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 31, 1, 108903, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 31, 1, 107899), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 31, 1, 107899, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 15, 31, 1, 98905), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 12, 31, 1, 99904, tzinfo=datetime.timezone.utc), verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 12, 31, 1, 99904, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
    ]
