# Generated by Django 5.0.3 on 2024-09-12 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_receits_state_alter_amountadjusting_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='finishDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('totalSales', models.FloatField(default=0, verbose_name='Total Sales')),
                ('systemMoney', models.FloatField(default=0, verbose_name='POS Money')),
                ('initialMoney', models.FloatField(default=0, verbose_name='Initial Money will be')),
                ('Date', models.DateField(default=datetime.datetime(2024, 9, 12, 16, 50, 37, 739869, tzinfo=datetime.timezone.utc), verbose_name='Date')),
                ('time', models.TimeField(default=datetime.datetime(2024, 9, 12, 16, 50, 37, 739869, tzinfo=datetime.timezone.utc), verbose_name='Time')),
                ('dateTime', models.DateTimeField(default=datetime.datetime(2024, 9, 12, 16, 50, 37, 739869, tzinfo=datetime.timezone.utc), verbose_name='DateTime')),
                ('breakPoint', models.IntegerField(default=0, verbose_name='Break Point')),
            ],
            options={
                'verbose_name_plural': 'Finish Day',
            },
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 19, 50, 37, 736870), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 16, 50, 37, 736870, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 19, 50, 37, 732875), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 16, 50, 37, 732875, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 19, 50, 37, 734873), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 16, 50, 37, 735871, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 19, 50, 37, 733872), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 16, 50, 37, 733872, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 19, 50, 37, 736870), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 16, 50, 37, 736870, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 19, 50, 37, 734873), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 16, 50, 37, 734873, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 19, 50, 37, 738869), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 16, 50, 37, 738869, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 19, 50, 37, 737870), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 16, 50, 37, 737870, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 12, 19, 50, 37, 731873), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 16, 50, 37, 731873, tzinfo=datetime.timezone.utc), verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 12, 16, 50, 37, 731873, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
    ]
