# Generated by Django 5.0.3 on 2024-09-14 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_finishday_alter_amountadjusting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receits',
            name='isbonus',
            field=models.BooleanField(default=False, verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 18, 39, 48, 485845), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 14, 15, 39, 48, 485845, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 18, 39, 48, 482847), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 14, 15, 39, 48, 482847, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishday',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 15, 39, 48, 488843, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishday',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 15, 39, 48, 488843, tzinfo=datetime.timezone.utc), verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='finishday',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 14, 15, 39, 48, 488843, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 18, 39, 48, 484846), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 14, 15, 39, 48, 484846, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 18, 39, 48, 483846), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 14, 15, 39, 48, 483846, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 18, 39, 48, 485845), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 14, 15, 39, 48, 485845, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 18, 39, 48, 483846), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 14, 15, 39, 48, 483846, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 18, 39, 48, 487844), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 14, 15, 39, 48, 487844, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 18, 39, 48, 486844), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 14, 15, 39, 48, 486844, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 18, 39, 48, 481848), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 14, 15, 39, 48, 481848, tzinfo=datetime.timezone.utc), verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 9, 14, 15, 39, 48, 481848, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
    ]
