# Generated by Django 5.0.3 on 2025-04-15 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_amountadjusting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountadjusting',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 12, 41, 233008), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 12, 41, 233008, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 12, 41, 230010), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 12, 41, 230010, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishday',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 18, 12, 41, 235007, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishday',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 18, 12, 41, 235007, tzinfo=datetime.timezone.utc), verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='finishday',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 12, 41, 235007, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 12, 41, 232008), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 12, 41, 232008, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 12, 41, 231009), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 12, 41, 231009, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 12, 41, 232008), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 12, 41, 232008, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 12, 41, 231009), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 12, 41, 231009, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 12, 41, 234007), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 12, 41, 234007, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 12, 41, 233008), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 12, 41, 233008, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 12, 41, 229011), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 18, 12, 41, 229011, tzinfo=datetime.timezone.utc), verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 12, 41, 229011, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
    ]
