# Generated by Django 5.0.3 on 2025-04-15 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_alter_amountadjusting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountadjusting',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 16, 56, 648503), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='amountadjusting',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 16, 56, 648503, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 16, 56, 646504), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='deletedreceits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 16, 56, 646504, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishday',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 18, 16, 56, 650502, tzinfo=datetime.timezone.utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishday',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 18, 16, 56, 650502, tzinfo=datetime.timezone.utc), verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='finishday',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 16, 56, 650502, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 16, 56, 647503), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='finishinghistory',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 16, 56, 647503, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 16, 56, 646504), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gavedmoney',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 16, 56, 646504, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 16, 56, 647503), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gotover',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 16, 56, 647503, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 16, 56, 646504), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='inoutemployeehistory',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 16, 56, 646504, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 16, 56, 649502), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_booking',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 16, 56, 649502, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 16, 56, 648503), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='marakez_receits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 16, 56, 648503, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='Date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 20, 16, 56, 644505), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 15, 18, 16, 56, 644505, tzinfo=datetime.timezone.utc), verbose_name='DateTime'),
        ),
        migrations.AlterField(
            model_name='receits',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 4, 15, 18, 16, 56, 644505, tzinfo=datetime.timezone.utc), verbose_name='Time'),
        ),
    ]
